### ISSUE TITLE
Solved Exercises

### ISSUE THREAD

**Issue by rubencg195** [rragundez/PyDataAmsterdam2018#2]
@rragundez can you upload in a separate notebook, the code for the solved exercises to have them as reference,  thanks in advance.

**Comment by paesibassi** [comment]
@rubencg195 the solutions of the excercises is in the `utils.py` file: https://github.com/rragundez/PyDataAmsterdam2018/blob/master/utils.py

**Comment by rubencg195** [comment]
Thank you very much @paesibassi.
