### ISSUE TITLE
Getting value error 

### ISSUE THREAD

**Issue by menon92** [rragundez/PyDataAmsterdam2018#3]
Hello @rragundez, 
I'm trying to run your notebook  `03_basics_of_keras_sequential_api.ipynb` but getting ValueError When executing `model.summary()` line 
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-9a7881f870d4> in <module>()
----> 1 model.summary()

~/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in summary(self, line_length, positions, print_fn)
   1261         if not self.built:
   1262             raise ValueError(
-> 1263                 'This model has never been called, this its weights '
   1264                 'have not yet been created, so no summary can be displayed. '
   1265                 'Build the model first '

ValueError: This model has never been called, this its weights have not yet been created, so no summary can be displayed. Build the model first (e.g. by calling it on some test data).
```

Thanks

**Comment by rragundez** [comment]
Well, I don't know the specifics of this problem but the error message indicates that the model has not been instantiated it so it doesn't know about the weights. I guess something like that.

**Comment by mihaim** [comment]
Getting the same error as Mehadi: 

After 

model.add(layers.Dense(name='FullyConnected_1', units=3, activation='relu', input_dim=2))

which looks fine to me, I get on 

model.summary()

ValueError: This model has never been called, thus its weights have not yet been created, so no summary can be displayed. Build the model first (e.g. by calling it on some test data).

Did nothing else than clone the notebook and try to run it 

LE It's something related to that particular notebook. When I moved the code to a separate notebook for debug it worked as expected: 

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
FullyConnected_1 (Dense)     (None, 3)                 9         
=================================================================
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________

**Comment by rragundez** [comment]
probably you are missing the `input_shape` parameter in the first layer added to the model

**Comment by menon92** [comment]
@rragundez ,
Could you please update your notebook so that we can run it without this error 

Thanks in Advance

**Comment by rragundez** [comment]
you can make a PR wit the change, I would gladly merge it.

**Comment by menon92** [comment]
Hello @mihaim @rragundez, 

I got the solution of this problem. Just don't execute the cell containing this code,

```python
# this should raise a ValueError
model.add(layers.Dense(name='FullyConnected_1', units=3, activation='relu')) 
```
and everything will be ok. the above line was the culprit.

Thanks
